---
title: "240316 Anaerobic Growth of E. coli in chow media conditions"
author: "Morgan Su"
date: "`r format(Sys.time(), '%a, %b %d, %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Setup

## Imports

```{r, echo=FALSE}
# Install additional packages not already in renv.lock
install.packages("readxl",
                 "ggthemes",
                 "RColorBrewer")

# Load libraries
library(dplyr)
library(ggplot2)
library(magrittr)
library(readr)
library(tidyr)
library(readxl)
library(ggthemes)
library(RColorBrewer)

# Update project lockfile if any changes were made
renv::snapshot()
```

## Parameters

```{r, echo=FALSE}
# Source locations
src_dir <- paste0("~/Documents/Stanford/Huang_lab_rotation/Chow_derived_media/",
                  "240316_anaerobic_ecoli_chow_conditions")
file <- "240314_ecoli_chow_anaerobic.xlsx"

# Destination locations
dst_dirname <- "outputs"
```

------------------------------------------------------------------------

# Data import

```{r}
# Read all csv files
anaerobic_chow_ <- read_excel(file.path(src_dir, file))
write.csv(anaerobic_chow_, paste0(sub("\\.xlsx$", "", file), ".csv"), 
          row.names = FALSE)
```

------------------------------------------------------------------------

# Computation

## Raw data transformation

```{r}
# Clone raw data
anaerobic_chow <- anaerobic_chow_

# Convert time column to POSIXct format and extract minutes and seconds
anaerobic_chow$Time <- as.POSIXct(anaerobic_chow$Time)
anaerobic_chow$Time <- as.numeric(format(anaerobic_chow$Time, "%M")) + 
  as.numeric(format(anaerobic_chow$Time, "%S")) / 60

# Remove temperature column
anaerobic_chow <- anaerobic_chow %>%
  select(-"T° 600")

# Specify relevant columns
anaerobic_chow <- select(anaerobic_chow, c(Time, E1:H12))

# Preview cleaned table
head(anaerobic_chow, 20)
```

## Table manipulation

```{r}
# Define conditions of the growth curve in a list
conditions <- list("BHI", "BHIS", "BHISD7", "BHISD7.ac", "15chowSD7.pbs", 
                   "15chowSD7.pbs.ac", "15chowSD7.pb", "15chowSD7.pb.ac", 
                   "BHIS+15chowSD7.pbs", "BHIS+15chowSD7.pbs.ac", 
                   "BHIS+15chowSD7.pb", "BHIS+15chowSD7.pb.ac")

# Iterate through each entry in "conditions" and add as a new column in df
for (i in seq_along(conditions)) {
  column_name <- conditions[[i]]
  column_values <- rowMeans(select(anaerobic_chow, 
                                   paste0("E", i), 
                                   paste0("F", i), 
                                   paste0("G", i)))
  blanks <- anaerobic_chow[[paste0("H", i)]]
  anaerobic_chow[[column_name]] <- column_values - blanks
}

# Remove non-averaged columns
anaerobic_chow_avg <- select(anaerobic_chow, -c("E1":"H12"))

# Preview averaged table
head(anaerobic_chow_avg)
```

```{r}
# Create table to calculate derivatives (growth rate)


```

------------------------------------------------------------------------

# Visualizations

## Growth curve

```{r}
# Plot

# Define conditions of the growth curve as a df
conditions_df <- as.data.frame(conditions, check.names = FALSE) 

gc <- ggplot(anaerobic_chow_avg, aes(x = Time)) +
  geom_line(aes(y = .data$'BHIS'), col = "darkred")

gc
```


# Save
ggsave(
  file.path(dst_dirname, "membrane_histogram.pdf"),
  membrane_histogram,
  height = 4,
  width = 6
)

# Print
membrane_histogram
```


## Images

I am choosing an image on the following criteria: 1. xxx 2. xxx 3. ...

On the basis of this criteria, I will be illustrating the following image:

```{r}
# Choose image
from_experiment <- "../../data/intermediate/exp=membrane-permeabilization/"
from_condition <- "detergent=digitonin_conc=0.02mmolar_minutes=1/"
from_basename <- "date=2022-03-19_488=poc5_594=cnb_01_01.tif"

# Copy paste to output directory
from <- file.path(from_experiment, from_condition, from_basename)
to <- file.path(dst_dirname, "example_image.tif")
file.copy(from, to)
```


------------------------------------------------------------------------

# Compute - Analyze

This is where you can compute any p-values.


------------------------------------------------------------------------

# Write

```{r}
```


------------------------------------------------------------------------

# Reproducibility

## Linting and styling

```{r}
# Style current file
styler::style_file(
  path = rstudioapi::getSourceEditorContext()$path,
  style = tidyverse_style
)

# Lint current file
lintr::lint(rstudioapi::getSourceEditorContext()$path)
```


## Dependencies

```{r}
# Clean up project of libraries not in use
renv::clean()

# Update lock file with new packages
renv::snapshot()
```


## Containerization

```{r}
# Only run this if option is set to TRUE
if (UPDATE_DOCKERFILE) {
  # Create a dockerfile from the session info
  my_dockerfile <- containerit::dockerfile(from = sessionInfo(), env = ls())
  # Write file
  write(my_dockerfile, file = "~/Dockerfile")
}

print(my_dockerfile)
```


------------------------------------------------------------------------

# Documentation

## Session info

```{r}
print(sessionInfo(), locale = FALSE)
```

## References

```{r}
(.packages()) %>%
  sort() %>%
  lapply(citation) %>%
  lapply(c) %>%
  unique()
```
